# Generated by Django 5.1.3 on 2026-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS bronze;'),
        migrations.CreateModel(
            name='BronzeLayer',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('booking_status', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelled_rides_by_customer', models.SmallIntegerField(blank=True, null=True)),
                ('reason_for_cancelling_by_customer', models.TextField(blank=True, null=True)),
                ('cancelled_rides_by_driver', models.SmallIntegerField(blank=True, null=True)),
                ('driver_cancellation_reason', models.TextField(blank=True, null=True)),
                ('incomplete_rides', models.SmallIntegerField(blank=True, null=True)),
                ('incomplete_rides_reason', models.TextField(blank=True, null=True)),
                ('booking_value', models.FloatField(blank=True, null=True)),
                ('ride_distance', models.FloatField(blank=True, null=True)),
                ('driver_ratings', models.FloatField(blank=True, null=True)),
                ('customer_rating', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"bronze"."raw_dataset"',
                'managed': True,
            },
        ),
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS silver;'),
        migrations.CreateModel(
            name='SilverLayer',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('day_of_week', models.CharField(max_length=20, null=True)),
                ('booking_status', models.CharField(max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
                ('cancelled_rides_by_driver', models.SmallIntegerField(default=0)),
                ('cancelled_rides_by_customer', models.SmallIntegerField(default=0)),
                ('incomplete_rides', models.SmallIntegerField(default=0)),
                ('unified_cancellation_reason', models.TextField(null=True)),
                ('booking_value', models.FloatField(blank=True, null=True)),
                ('ride_distance', models.FloatField(blank=True, null=True)),
                ('driver_ratings', models.FloatField(null=True)),
                ('customer_rating', models.FloatField(null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"silver"."cleaned_dataset"',
                'managed': True,
            },
        ),
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS Gold;'),
        migrations.CreateModel(
            name='GoldLayer',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('day_of_week', models.CharField(max_length=20, null=True)),
                ('booking_status', models.CharField(max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
                ('cancelled_rides_by_driver', models.SmallIntegerField(default=0)),
                ('cancelled_rides_by_customer', models.SmallIntegerField(default=0)),
                ('incomplete_rides', models.SmallIntegerField(default=0)),
                ('unified_cancellation_reason', models.TextField(null=True)),
                ('booking_value', models.FloatField(blank=True, null=True)),
                ('ride_distance', models.FloatField(blank=True, null=True)),
                ('revenue_per_km', models.FloatField(blank=True, null=True)),
                ('driver_ratings', models.FloatField(null=True)),
                ('customer_rating', models.FloatField(null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '"gold"."dataset"',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('driver_ratings__gte', 0), ('driver_ratings__lte', 5)), ('driver_ratings__isnull', True), _connector='OR'), name='driver_rating_range'), models.CheckConstraint(condition=models.Q(models.Q(('customer_rating__gte', 0), ('customer_rating__lte', 5)), ('customer_rating__isnull', True), _connector='OR'), name='customer_rating_range')],
            },
        ),
    ]
